// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.2
// source: port.proto

package protobuff

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// UpsertClient is the client API for Upsert service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UpsertClient interface {
	Upsert(ctx context.Context, in *SeaPort, opts ...grpc.CallOption) (*Status, error)
}

type upsertClient struct {
	cc grpc.ClientConnInterface
}

func NewUpsertClient(cc grpc.ClientConnInterface) UpsertClient {
	return &upsertClient{cc}
}

func (c *upsertClient) Upsert(ctx context.Context, in *SeaPort, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/nickax.upsert/upsert", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UpsertServer is the server API for Upsert service.
// All implementations must embed UnimplementedUpsertServer
// for forward compatibility
type UpsertServer interface {
	Upsert(context.Context, *SeaPort) (*Status, error)
	mustEmbedUnimplementedUpsertServer()
}

// UnimplementedUpsertServer must be embedded to have forward compatible implementations.
type UnimplementedUpsertServer struct {
}

func (UnimplementedUpsertServer) Upsert(context.Context, *SeaPort) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Upsert not implemented")
}
func (UnimplementedUpsertServer) mustEmbedUnimplementedUpsertServer() {}

// UnsafeUpsertServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UpsertServer will
// result in compilation errors.
type UnsafeUpsertServer interface {
	mustEmbedUnimplementedUpsertServer()
}

func RegisterUpsertServer(s grpc.ServiceRegistrar, srv UpsertServer) {
	s.RegisterService(&Upsert_ServiceDesc, srv)
}

func _Upsert_Upsert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SeaPort)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpsertServer).Upsert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nickax.upsert/upsert",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpsertServer).Upsert(ctx, req.(*SeaPort))
	}
	return interceptor(ctx, in, info, handler)
}

// Upsert_ServiceDesc is the grpc.ServiceDesc for Upsert service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Upsert_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nickax.upsert",
	HandlerType: (*UpsertServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "upsert",
			Handler:    _Upsert_Upsert_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "port.proto",
}
